[build]
# Set backend as the root for the Python buildpack to work correctly
root = "backend"

[phases.build]
# Install PHP dependencies
cmds = ["composer install --optimize-autoloader --no-dev --no-ansi --no-interaction"]

[phases.release]
# Run migrations and cache
cmds = ["php artisan migrate --force --no-ansi && php artisan cache:clear && php artisan config:cache && php artisan route:cache"]

[[processes]]
name = "web"
cmd = "vendor/bin/heroku-php-apache2 public/ -F fpm_config.ini"
