[build]
# Direcrorio raíz del proyecto
root = "backend"

[phases.build]
# Build PHP dependencies
dependsOn = ["setup"]
cmds = ["composer install --optimize-autoloader --no-dev --no-ansi --no-interaction"]

[phases.setup]
# Setup PHP environment
cmds = ["php --version && composer --version"]

[processes.web]
# Web server process
cmd = "vendor/bin/heroku-php-apache2 public/ -F fpm_config.ini"

[processes.release]
# Migration and caching process (runs once during deployment)
cmd = "php artisan migrate --force --no-ansi && php artisan cache:clear && php artisan config:cache && php artisan route:cache"
